# Generated by Django 5.1.3 on 2024-12-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toimittaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yritysnimi', models.CharField(default='yritysnimi', max_length=50)),
                ('yhteyshenkilö', models.CharField(default='yhteyshenkilö', max_length=50)),
                ('osoite', models.CharField(default='osoite', max_length=100)),
                ('puhelin', models.CharField(default='puhelin', max_length=20)),
                ('sähköposti', models.CharField(default='sähköposti', max_length=50)),
                ('maa', models.CharField(default='maa', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Varasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuotenimi', models.CharField(max_length=20)),
                ('painoperkappale', models.CharField(max_length=20)),
                ('kappalehinta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tuotteitavarastossa', models.IntegerField()),
                ('toimittaja_nimi', models.CharField(blank=True, max_length=50, null=True)),
                ('toimittaja_maa', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuotenimi', models.CharField(default='tuotenimi', max_length=20)),
                ('painoperkappale', models.CharField(default=3, max_length=20)),
                ('kappalehinta', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('tuotteitavarastossa', models.IntegerField(default=3)),
                ('toimittaja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.toimittaja')),
            ],
        ),
    ]
