databases:
  - name: toimittajadb
    plan: free
    databaseName: Kurssi
    user: niklas

services:
  - type: web
    plan: free
    name: Kurssi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Kurssi.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: toimittajadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: "niklas"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "testaaja"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "super@usersuper.fi"